"use client";

import Link from "next/link";
import {
  Home,
  BriefcaseBusiness,
  CarFront,
  IndianRupee,
  MapPin,
  Tag,
} from "lucide-react";

export default function BottomBar() {
  return (
    <nav
      className="
        fixed
        inset-x-0
        bottom-0
        z-[9997]
        block
        border-t
        border-white/10
        bg-[var(--primary)]
        md:hidden
        font-[var(--font-jakarta)]
      "
    >
      <div
        className="
          grid
          h-16
          w-full
          grid-cols-6
          bg-[var(--primary)]
        "
      >
        {/* HOME */}
        <Link
          href="/"
          className="
            group
            flex
            flex-col
            items-center
            justify-center
            gap-1
            ! text-white
            transition-colors
            duration-200
            hover:text-[var(--secondary)]
            active:text-[var(--secondary)]
          "
        >
          <Home
            className="
              h-5
              w-5
              transition-colors
              duration-200
              group-hover:text-[var(--secondary)]
            "
          />

          <span
            className="
              text-[10px]
              font-medium
              transition-colors
              duration-200
              group-hover:text-[var(--secondary)]
            "
          >
            Home
          </span>
        </Link>

        {/* SERVICES */}
        <Link
          href="/services"
          className="
            group
            flex
            flex-col
            items-center
            justify-center
            gap-1
            !text-white
            transition-colors
            duration-200
            hover:text-[var(--secondary)]
            active:text-[var(--secondary)]
          "
        >
          <BriefcaseBusiness
            className="
              h-5
              w-5
              transition-colors
              duration-200
              group-hover:text-[var(--secondary)]
            "
          />

          <span
            className="
              text-[10px]
              font-medium
              transition-colors
              duration-200
              group-hover:text-[var(--secondary)]
            "
          >
            Services
          </span>
        </Link>

        {/* FLEET */}
        <Link
          href="/fleet"
          className="
            group
            flex
            flex-col
            items-center
            justify-center
            gap-1
            !text-white
            transition-colors
            duration-200
            hover:text-[var(--secondary)]
            active:text-[var(--secondary)]
          "
        >
          <CarFront
            className="
              h-5
              w-5
              transition-colors
              duration-200
              group-hover:text-[var(--secondary)]
            "
          />

          <span
            className="
              text-[10px]
              font-medium
              transition-colors
              duration-200
              group-hover:text-[var(--secondary)]
            "
          >
            Fleet
          </span>
        </Link>

        {/* PRICING */}
        <Link
          href="/pricing"
          className="
            group
            flex
            flex-col
            items-center
            justify-center
            gap-1
            !text-white
            transition-colors
            duration-200
            hover:text-[var(--secondary)]
            active:text-[var(--secondary)]
          "
        >
          <IndianRupee
            className="
              h-5
              w-5
              transition-colors
              duration-200
              group-hover:text-[var(--secondary)]
            "
          />

          <span
            className="
              text-[10px]
              font-medium
              transition-colors
              duration-200
              group-hover:text-[var(--secondary)]
            "
          >
            Pricing
          </span>
        </Link>

        {/* DESTINATIONS */}
        <Link
          href="/destinations"
          className="
            group
            flex
            flex-col
            items-center
            justify-center
            gap-1
            !text-white
            transition-colors
            duration-200
            hover:text-[var(--secondary)]
            active:text-[var(--secondary)]
          "
        >
          <MapPin
            className="
              h-5
              w-5
              transition-colors
              duration-200
              group-hover:text-[var(--secondary)]
            "
          />

          <span
            className="
              text-[10px]
              font-medium
              transition-colors
              duration-200
              group-hover:text-[var(--secondary)]
            "
          >
            Destinations
          </span>
        </Link>

        {/* OFFERS */}
        <Link
          href="/offers"
          className="
            group
            flex
            flex-col
            items-center
            justify-center
            gap-1
            !text-white
            transition-colors
            duration-200
            hover:text-[var(--secondary)]
            active:text-[var(--secondary)]
          "
        >
          <Tag
            className="
              h-5
              w-5
              transition-colors
              duration-200
              group-hover:text-[var(--secondary)]
            "
          />

          <span
            className="
              text-[10px]
              font-medium
              transition-colors
              duration-200
              group-hover:text-[var(--secondary)]
            "
          >
            Offers
          </span>
        </Link>
      </div>
    </nav>
  );
}